services:
  - type: web
    name: aihcas
    runtime: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng python3 python3-pip && pip3 install pytesseract Pillow pymupdf && npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TESSERACT_PATH
        value: /usr/bin/tesseract
